FROM iron/base
LABEL Description="This image is used to host the secure file helper tools" \ 
      Maintainer="airenass@gmail.com" Vendor="Airenas Vaiciunas" Version="1.0" 

WORKDIR /app

COPY data/encrypt-file /app/
COPY data/check-decrypt-file /app/
